---
- name: Base Domain Variable Check
  debug:
    msg: "{{ lookup('env', 'CDLAB_BASE_DOMAIN') }}"

- name: Building Jenkins Version
  debug:
    msg: "{{ jenkins_version }}"

# -----------------------------
# docker-compose
# -----------------------------

- name: Create jenkins dir for docker-compose based installation
  file:
    path: /opt/docker/jenkins
    state: directory

- name: Setup jenkins docker-compose file
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/docker/jenkins/docker-compose.yml

# -----------------------------
# build
# -----------------------------

- name: Create jenkins build dir
  file:
    path: /opt/docker/jenkins/build
    state: directory

- name: Setup jenkins Dockerfile
  template:
    src: templates/Dockerfile.j2
    dest: /opt/docker/jenkins/build/Dockerfile

- name: Setup jenkins plugins.txt
  template:
    src: templates/plugins.txt.j2
    dest: /opt/docker/jenkins/build/plugins.txt

- name: Setup jenkins casc.yaml
  template:
    src: templates/casc.yaml.j2
    dest: /opt/docker/jenkins/build/casc.yaml

- name: get docker group id
  shell: "getent group docker|cut -d: -f3"
  register: docker_gid

- name: Build custom jenkins image
  docker_image:
    build:
      path: /opt/docker/jenkins/build
      args:
        DOCKER_GROUP_ID: "{{ docker_gid.stdout }}"
    name: jenkins:{{ jenkins_version }}-jcasc
    source: build
    state: present

# -----------------------------
# persistence
# -----------------------------

- name: Create jenkins storage dir
  file:
    path: /opt/docker/jenkins/storage
    state: directory

- name: Create jenkins storage mount dir 
  file:
    path: /opt/docker/jenkins/storage/jenkins_home
    state: directory
    group: "1000"
    owner: "1000"
    mode: 0755

- name: Create jenkins letsencrypt mount dir 
  file:
    path: /opt/docker/jenkins/storage/letsencrypt
    state: directory

# -----------------------------
# Jenkins setup
# -----------------------------
- name: Setup locale
  template:
    src: templates/locale.xml.j2
    dest: /opt/docker/jenkins/storage/jenkins_home/locale.xml
    group: "1000"
    owner: "1000"

- name: Create jenkins .ssh dir
  file:
    path: /opt/docker/jenkins/storage/jenkins_home/.ssh
    state: directory
    group: "1000"
    owner: "1000"
    mode: 0700
  
- name: Copy service_user ssh private key
  copy:
    src: ~/.heiseacademy/id_rsa-serviceuser
    dest: /opt/docker/jenkins/storage/jenkins_home/.ssh/id_rsa-serviceuser
    owner: "1000"
    group: "1000"
    mode: 0600
    backup: yes

- name: Copy provisioning user ssh private key
  copy:
    src: ~/.heiseacademy/id_rsa
    dest: /opt/docker/jenkins/storage/jenkins_home/.ssh/id_rsa
    owner: "1000"
    group: "1000"
    mode: 0600

- name: Create .heiseacademy config dir
  file:
    path: /opt/docker/jenkins/storage/jenkins_home/.heiseacademy
    state: directory
    group: "1000"
    owner: "1000"
    mode: 0700

- name: Copy contents of .heiseacademy config dir
  copy:
    src: ~/.heiseacademy/
    dest: /opt/docker/jenkins/storage/jenkins_home/.heiseacademy/
    owner: "1000"
    group: "1000"

# -----------------------------
# Start Services
# -----------------------------

- name: Create and start services
  community.general.docker_compose:
    project_src: /opt/docker/jenkins
  # register: output

# - name: Debug docker-compose up
#   debug:
#     var: output
