jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
        - id: user
          password: user
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Administer:user"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
unclassified:
  location:
    url: http://jenkins:8080/
