---
- name: Install a list of packages
  apt:
    name: "unattended-upgrades"
    update_cache: yes

- name: configure apt
  template:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    src: templates/50unattended-upgrades.j2
    mode: 0644
    owner: root
    group: root
