---
- import_tasks: disable_ipv6.yml
- import_tasks: configure_locale.yml
- import_tasks: configure_vimrc.yml
- import_tasks: configure_apt.yml
# - import_tasks: setup_users.yml

- name: Install a list of packages
  apt:
    name: "{{ common_packages }}"
    update_cache: yes

- name: Install docker and docker-compose
  import_role:
    name: geerlingguy.docker
- name: Install docker-python library
  vars:
    pip_install_packages:
    - name: docker
    - name: docker-compose
  import_role:
    name: geerlingguy.pip

- name: create common dir for docker-compose based installations
  file:
    path: /opt/docker
    state: directory

# TODO: make docker-compose version configurable (as of now it's hardcoded here and in roles/geerlingguy.docker)
- name: add bash-completion for docker-compose
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/1.28.5/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    mode: '0644'
