---
- name: Make sure we have a 'serviceuser' group
  group:
    name: serviceuser
    state: present
  tags:
    - serviceuser_setup

- name: Allow 'serviceuser' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%serviceuser'
    line: '%serviceuser ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  tags:
    - serviceuser_setup

# - name: Add ssh key to serviceusers authorized_keys
#   authorized_key:
#     user: serviceuser
#     key: 
#   tags:
#     - serviceuser_setup

# - name: Save private github capable ssh key as /root/.ssh/id_rsa

#   tags:
#     - user_setup