---
- name: apply common configuration to all nodes (ie docker, docker-compose)
  hosts: all
  pre_tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
  # vars_files:
  #   - "./vars/users.yml"
  roles:
    - role: common
      tags: docker, common
- name: provision jenkins
  hosts: jenkins
  roles:
    - role: jenkins
      tags: jenkins
- name: provision gitlab
  hosts: gitlab
  roles:
    - role: gitlab
      tags: gitlab
