---
- name: apply common configuration to all nodes (ie docker, docker-compose)
  hosts: all
  roles:
    - role: common
      tags: docker, common
- name: provision jenkins
  hosts: jenkins
  roles:
    - role: jenkins
      tags: jenkins
- name: provision gitlab
  hosts: gitlab
  vars:
    cdlab_proxied: "{{ lookup('env', 'CDLAB_PROXIED') | default('0', True)}}"
  roles:
    - role: gitlab
      tags: gitlab
